const SAFETY_ORANGE = '#FE6400'
const KILAMANJARO = '#3C3935'
const NERO = '#272727'
const BLUE_CHARCOAL = '#222529'
const DIM_GREY = '#6E6E6E'
const VERY_LIGHT_GREY = '#6E6E6E'
const WHITE_SMOKE = '#F9F9F9'
const WHITE = '#FFFFFF'

const PRIMARY = SAFETY_ORANGE
const SECONDARY = KILAMANJARO
const PRIMARY_TEXT = WHITE
const SECONDARY_TEXT = WHITE

export default {
  PRIMARY,
  SECONDARY,
  PRIMARY_TEXT,
  SECONDARY_TEXT,
  SAFETY_ORANGE,
  KILAMANJARO,
  NERO,
  BLUE_CHARCOAL,
  DIM_GREY,
  VERY_LIGHT_GREY,
  WHITE_SMOKE,
  WHITE,
}
